Quiet down cherry-pick integration spec
This spec was printing out messages like:

    error: could not apply 79d0feb... Add Branch 2 addition
    hint: after resolving the conflicts, mark the corrected paths
    hint: with 'git add <paths>' or 'git rm <paths>'
    hint: and commit the result with 'git commit'

To prevent the spec suite from having noisy output, redirect STDERR for
the cherry-picking code to /dev/null.

Change-Id: Iba67b179cf4e0f87f805cb28a362ba276658b24c
Reviewed-on: http://gerrit.causes.com/38490
Tested-by: jenkins <jenkins@causes.com>
Reviewed-by: Shane da Silva <shane@causes.com>